fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        search:
            finder: ~
            client: default
            types:
                ads:
                    mappings:
                        id:
                            type: integer
                        title: ~
                        object_status:
                            type: string
                            fielddata: true
                        delivery_method:
                            type: string
                            fielddata: true
                        categories:
                            type: nested
                            properties :
                              id:
                                type: integer
                              title:
                                type: string
                                index: not_analyzed
                        price:
                            type: nested
                            properties :
                              id:
                                type: integer
                              price_type:
                                type: string
                                fielddata: true
                              amount:
                                type: double
                        location:
                            type: nested
                            properties :
                              id:
                                type: integer
                              zipcode:
                                type: nested
                                properties :
                                  id:
                                    type: integer
                                  province:
                                    type: nested
                                    properties :
                                      id:
                                        type: integer
                                      name:
                                        type: string
                                        index: not_analyzed
                    persistence:
                        driver: orm
                        model: Baazaar\BaazaarBundle\Entity\Ad
                        finder: ~
                        provider: ~
                        listener: ~
                categories:
                    mappings:
                        id:
                          type: integer
                        title: ~
                    persistence:
                        driver: orm
                        model: Baazaar\BaazaarBundle\Entity\Category
                        finder: ~
                        provider: ~
                        listener: ~
                price:
                    mappings:
                        id:
                          type: integer
                        price_type:
                          type: string
                          fielddata: true
                        amount:
                          type: double
                    persistence:
                        driver: orm
                        model: Baazaar\BaazaarBundle\Entity\Price
                        finder: ~
                        provider: ~
                        listener: ~
                place:
                    mappings:
                        name:
                          type: string
                          fielddata: true
                        zipcode:
                          type: nested
                          properties :
                            zip:
                              type: string
                              fielddata: true
                    persistence:
                        driver: orm
                        model: Baazaar\LocationBundle\Entity\Place
                        finder: ~
                        provider: ~
                        listener: ~
