# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_to_username_transformer:
        class: Baazaar\UserBundle\Form\DataTransformer\UserToUsernameTransformer
        arguments:
            - "@doctrine"
    fos_user.user_to_username_transformer:
        alias: app.user_to_username_transformer
