<?php

namespace Baazaar\LocationBundle\Repository;

/**
 * ZipcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipcodeRepository extends \Doctrine\ORM\EntityRepository
{
}
