services:
  baazaar.form.type.view:
        class: Baazaar\BaazaarBundle\Form\AdType
        arguments: [ "@doctrine" ]
        tags:
            - { name: form.type, alias: form_ad }
  baazaar.elasticSearchHelper:
        class: Baazaar\BaazaarBundle\Services\ElasticSearchHelper
        arguments: ['@service_container']
