<?php

namespace Baazaar\BaazaarBundle\Repository;

/**
 * AdReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdReportRepository extends \Doctrine\ORM\EntityRepository
{
}
